services:
  bank-api:
    image: wiremock/wiremock:3.13.1
    command: --disable-http2-plain
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/bank:/home/wiremock

  report-api:
    image: wiremock/wiremock:3.13.1
    command: --disable-http2-plain
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/report:/home/wiremock

  money-flow:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONEY_FLOW_BANK_STATEMENT_API_BASE_URL: http://bank-api:8080
      MONEY_FLOW_BALANCE_REPORT_API_BASE_URL: http://report-api:8080
    depends_on:
      - bank-api
      - report-api
